# Generated by Django 3.0.3 on 2020-06-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Droplet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
    ]
